name: Publish Image

permissions:
    id-token: write
    contents: read
on:
  workflow_run:
    workflows: ["Docker"]
    types: [completed]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_sha || github.sha}}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{secrets.AWS_PUBLISH_ROLE}}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2      

      - name: Check ECR publish permissions
        run: |
          aws ecr batch-get-image --repository-name redlike --image-ids imageTag=main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{steps.login-ecr.outputs.registry}}/redlike
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=branch

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          platforms: linux/amd64
          provenance: false
          sbom: false
